# Macbook-101-Ubuntu-server
Set up for Ubuntu Server on MBP 10.1
* Prior to installation
- Use OS X to create a Ubuntu server bootable USB
#+begin_src bash
hdiutil convert -format UDRW -o ~/path/to/target.img ~/path/to/ubuntu.iso
diskutil unmountDisk /dev/diskN
sudo dd if=/path/to/downloaded.img of=/dev/rdiskN bs=1m
#+end_src
- Install [[http://www.rodsbooks.com/refind/][Refind]]
- Shrink OS X partition
- Aquire a thunderbolt-ethernet adaptor

* Basic Installation
- Install Ubuntu Server with ethernet.
- On choosing partitioning - select the created partition and delete it. Then choose guided on the largest continuous free space.
#+begin_src bash
update and upgrade
apt-get install bcmwl-kernel-source
#+end_src
- edit /etc/init/failsafe.cong and comment out all lines relating to sleep to prevent stalling on startup without networking

* Wifi
- install wpasupplicant, if not already installed.
#+begin_src bash
apt-get install wpasupplicant
#+end_src
#+begin_src
wpapassphrase ssid psk >> /etc/wpa_supplicant.conf
#+end_src
- Add first line of wpa_supplicant.conf to read
#+begin_src bash
ctrl_interface=/run/wpa_supplicant
#+end_src
- edit =/etc/network/interfaces
#+begin_src bash
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto eth0
iface eth0 inet dhcp

auto wlan0
iface wlan0 inet dhcp
pre-up wpa_supplicant -Dnl80211 -iwlan0 -B -c/etc/wpa_supplicant/wpa_supplicant.conf
post-down killall -q wpa_supplicant
iface default inet dhcp
#+end_src
* Other packages
#+begin_src bash
apt-get install build-essential git imagemagick mutt openvpn git ssh xfce4-terminal youtube-dl vlc
#+end_src
* Emacs
#+begin_src bash
sudo apt-get build-dep emacs24
wget http://ftp.gnu.org/gnu/emacs/emacs-24.4.tar.xz
tar -xvf emacs-24.4.tar.xz
cd emacs-24.4
./configure
make
sudo make install
#+end_src
- take .emacs and .emacs.d from this repo
* Desktop
#+begin_src bash
echo 'deb http://build.i3wm.org/ubuntu/trusty trusty main' >> /etc/apt/sources.list
apt-get update
apt-get --allow-unauthenticated install i3-autobuild-keyring
apt-get update
apt-get install i3
#+end_src
- take =~/.i3/config= file from this repo
* Firefox
- Developers edition
#+begin_src bash
add-apt-repository ppa:ubuntu-mozilla-daily/firefox-aurora
apt-get update & apt-get install firefox
#+end_src
* DNS Setting
- To edit DNS - open =/etc/dhcp/dhclinet.conf=
#+begin_src bash
prepend domain-nam-servers 8.8.8.8,8/8/8/4; #for instance
#+end_src
* VPN
#+begin_src bash
apt-get install openvpn
#+end_src
* Sound
- Install alsa
#+begin_src bash
sudo apt-get install alsa
#+end_src
- note - might also need alsa-utils and alsa-tools????
- edit =etc/modprobe.d/alsa-base.conf= and add to the end
#+begin_src bash
options snd-hda-intel model=mbp101
#+end_src
- Then add yourself to the audio group
#+begin_src bash
sudo adduser UserName audio
#+end_src
* Fans
#+begin_src bash
add-apt-repository ppa:detly/mactel-utils
apt-get update
apt-get install macfanctld
#+end_src




